### ISSUE TITLE
Don't apply filtering to HUD/menu graphics

### ISSUE THREAD

**Issue by OpenRift412** [andrei-drexler/ironwail#100]
When enabling texture filtering, it should not apply to any 2D-rendered assets like the HUD, menu, or console grpahics. It can introduce some weird artifacting.

**Comment by andrei-drexler** [comment]
I think I'd rather fix the artifacts - 5f4eea3ee8043a3d2200998a8316082b8d95bb37 should do it.

Before:
![before](https://user-images.githubusercontent.com/5121829/176563539-42ff3d6e-1487-4f20-8b0f-4c092844730f.png)
After:
![after](https://user-images.githubusercontent.com/5121829/176563557-922baace-3751-42a6-98f7-dab2745e2d8d.png)

**Comment by mhQuake** [comment]
There's still one case - textbox borders - which is susceptible to artifacts when linear filtering is applied. This didn't happen in GLQuake because it forced nearest filtering on the charset texture, and won't happen on any port that likewise uses nearest filtering for it. But if you do put linear filtering on the charset you'll get it.

It's most noticeable on textbox borders, but it actually generalises to any character which has texels at the edge of it's 8x8 subregion, and characters that are adjacent to it.

For the textbox borders, the 2x2 block used with linear filtering can introduce transparent texels from a neighbouring character when the texture is sampled, so at certain resolutions and scaling factors the border has gaps in it.

For other characters the effect can go the other way, with solid texels from a neighbouring character being introduced to what should be a transparent area.

An easy way to resolve this is to use a 256 slice array texture for the charset, but it needs another shader permutation.

Otherwise just don't use linear filtering on the charset.

**Comment by andrei-drexler** [comment]
I'm not really sure what you mean by texbox borders - is it the textbox drawn by M_DrawTextBox? Because that one uses separate pics, not characters, and clamping fixes the artifacts there, too:

Before:
![box_before](https://user-images.githubusercontent.com/5121829/176961086-0a59fde5-6eec-4c56-b806-70be5a385965.png)

After:
![box_after](https://user-images.githubusercontent.com/5121829/176961103-7f92607d-e66d-4e5a-9586-1340c7f35577.png)

As for the charset texture, that's always point-sampled (as can be seen in the FPS counter). Using an array texture is an interesting idea, though.

**Comment by mhQuake** [comment]
You're right, sorry - I got that mixed up with something else.
