### ISSUE TITLE
Cannot bind CAPS LOCK

### ISSUE THREAD

**Issue by daftmugi** [andrei-drexler/ironwail#104]
I cannot bind the capslock key, which is a key I use when I play games.

I consider this a bug, since it works fine in other games. And, it's hard to describe and request, because it's like asking to have the spacebar key, alt key, w-key, or any other common key be made bindable. The good thing is that the fix is roughly equivalent to adding the capslock key to a lookup table that has all of the bindable keys.

The main question I can think of with this is "but what about the capslock state?"

1. In my testing, the capslock state does not interfere with gameplay input. It only changes the capslock state for console input. That's how Quake/Ironwail is today without any changes.
2. I imagine that most players who would bind the capslock key would be using a special keyboard layout. For example, in Linux, `XKBOPTIONS="ctrl:nocaps"` can be set in the `/etc/default/keyboard` file. Then, the capslock key becomes a ctrl key (and does not change the capslock state or light). In macOS, it is trivial to change the capslock key to something else in its keyboard preferences.

Ironwail is using [SDL_Scancode](https://wiki.libsdl.org/SDL_Scancode) instead of [SDL_Keycode](https://wiki.libsdl.org/SDL_Keycode), so the physical keyboard input is used instead of the OS keyboard layout mapping for each key. Players are stuck and need each key explicitly bindable.

Support for binding the capslock key was added to vkQuake, so could support please be added to Ironwail as well?
Please see https://github.com/Novum/vkQuake/commit/8bfb38e34e8890005b83bbb4aa841315fd05bddf

Thank you for Ironwail and looking into this!

(Edited: I rewrote this issue to hopefully be clearer and easier to understand.)

**Comment by andrei-drexler** [comment]
Hey, thanks for the additional info, but you really didn't need to go through all this trouble. The issue was pretty clear from the start, I just needed a break from this project (and probably still do). Anyway, I added support for Caps Lock, Scroll Lock, Num Lock and Print Screen in https://github.com/andrei-drexler/ironwail/commit/0f0b54d955dcd749691e4a621b4a2babb928ec8c.

Longer term, I'll have to think about switching from scan codes to key codes. On the one hand it seems odd to require people using AZERTY to still bind W/A/S/D for movement (and show W/A/S/D in the UI when they're pressing Z/Q/S/D), but on the other hand, the current implementation kind of allows using the same default config on all keyboard layouts. Not really sure about the best solution yet.

**Comment by timbergeron** [comment]
Would it be possible to implement disable the caps lock  function? With it bindable it then will be on / off at unintended/unpredicted times affecting console input.

**Comment by andrei-drexler** [comment]
@timbergeron I've added a hook in https://github.com/andrei-drexler/ironwail/commit/af4adbe6f05472a97fcb5a7a4c38510b6d42dc18 - it will only intercept the \*lock keys during gameplay, or while waiting for a key binding in the controls menu.

**Comment by daftmugi** [comment]
@andrei-drexler Thank you so much for adding capslock support! I understand taking time away from a project, and I hope you're getting the rest that you need.

**Comment by timbergeron** [comment]
Very cool, thanks!
