### ISSUE TITLE
loading savegame files  with FTE particles 

### ISSUE THREAD

**Issue by j4reporting** [andrei-drexler/ironwail#107]
loading an  AD savegame file created wiith vkquake  results in an error  because some FTE particle effects are not  (yet?)  implemented in ironwail. Would it make sense to skip/ignore this additional particle data for now instead of reporting an error **and** aborting?

**Comment by andrei-drexler** [comment]
Unfortunately, it's not as simple as ignoring some data in the savefile. The problem is that AD checks for certain QuakeC extensions when the map is started and then caches the presence/absence of those features in variables that get serialized along with everything else. When the savefile is then loaded, AD doesn't know to check again if those extensions are still present, so it ends up calling unsupported functions. I don't think I can fix this one.
