### ISSUE TITLE
[Build] DEFAULT_TARGET is not recognized by GNU Make

### ISSUE THREAD

**Issue by 4LT** [andrei-drexler/ironwail#127]
From reading the Makefile, it seems that the default behavior of running `make` should be the same as `make release`.  Under GNU Make, this is not the case.  Setting DEFAULT_TARGET has no effect, so the first build target is used instead.  GNU Make instead recognizes `.DEFAULT_GOAL` (https://www.gnu.org/software/make/manual/html_node/Special-Variables.html#Special-Variables) to override the default target, but a more portable/conventional solution would be to add the target `all: release` to the top of the build targets.

**Comment by andrei-drexler** [comment]
It looks like the makefile has been like this since [the beginning](https://github.com/sezero/quakespasm/blob/097c46c8b2d311dcc517e972d95dacdf2b7ccec3/Quake/Makefile#L120), and got fixed in QS [pretty recently](https://github.com/sezero/quakespasm/commit/09216eb65f5407ba0a3161932db41c12031e6dc3). I synced with upstream in 13c299080d32dc470ec91f4bd7711d684fdd9d88, so now there's an `all: $(DEFAULT_TARGET)` target.
