### ISSUE TITLE
[Bug] Texture flickering

### ISSUE THREAD

**Issue by wirion** [andrei-drexler/ironwail#160]
Hi,
in e1m1 the secret elevator next to the quad secret has some texture weirdness going on when it's lowered (flush with the rest of the floor). As you look around, the pattern changes rapidly.
This is in ironwail 0.6.0 and later, but not in quakespasm 0.95.1.

![ironwail0000](https://user-images.githubusercontent.com/1149836/213753984-358a6b45-e8b1-41b2-bb16-e3b96b18435c.png)

**Comment by andrei-drexler** [comment]
Hey! There's a cvar for this, `gl_zfix 1`. It's actually 1 by default, but it's 0 in QS, and if already have a config.cfg with it off the first time IW is started then it'll stay off. Maybe I should rename it to r_zfix to avoid this situation.

**Comment by wirion** [comment]
Oh no, my bad, I totally turned that off when I initially didn't see a difference. Sorry to spam the Issues! But thanks for your response!

**Comment by andrei-drexler** [comment]
No problem!

I'm going to close this issue without renaming the cvar after all because I've realized that QS doesn't save it to config, so the only way this can happen is if it is indeed changed manually in IW. Ideally there would be some kind of documentation for these cvars, but I guess that's a different issue.
