### ISSUE TITLE
Popup text has lines under it. 

### ISSUE THREAD

**Issue by unkles31m** [andrei-drexler/ironwail#182]
![ironwail0002](https://user-images.githubusercontent.com/128260568/226141036-69c09177-c5a7-40b9-bd3e-bf8b9385c46a.png)

Popup texts occasionally have these lines under them. It's most noticeable in "Crypt" in this picture.

**Comment by andrei-drexler** [comment]
Is this with version 0.6 or 0.7? It should be fixed in 0.7, and the screenshot name would seem to indicate that this is from 0.6.

**Comment by unkles31m** [comment]
> Is this with version 0.6 or 0.7? It should be fixed in 0.7, and the screenshot name would seem to indicate that this is from 0.6.

My apologies, i have multiple different versions of Ironwail for testing purposes. 
Although im using the id1 file from the rerelease which seems to be the only file that caused this issue. Using the original id1 doesn't have this issue on Ironwail 0.6

**Comment by andrei-drexler** [comment]
No problem! Those artifacts were really bothering me, too, so 0.7 adds padding around characters specifically to avoid this issue. I think the difference between original and rerelease is likely because of slightly different UI scale values in the configs, it only happened at some particular values.
