### ISSUE TITLE
Shares config with quakespasm

### ISSUE THREAD

**Issue by Dreded** [andrei-drexler/ironwail#26]
This seems to share a config with quakespasm which causes all sorts of fun Resolution related issues, I ended up having to force close and delete the config settings, I'm guessing they have different names for a couple options in the same config.

**Comment by dumptruckDS** [comment]
Yes, would be very helpful to have ironwail.cfg for those of use checking mods and maps across different engines.

**Comment by andrei-drexler** [comment]
I've changed the config file name to `ironwail.cfg` in https://github.com/andrei-drexler/ironwail/commit/743f6b0354042c3b825fcb3035356bde8dca10da. Since `exec config.cfg` is normally found in `quake.rc` (beyond my control), I had to hack the `exec` command so that when `config.cfg` is specificied the code will first look for `ironwail.cfg` and execute that instead, and if that's not found, fall back to executing `config.cfg`. `ironwail.cfg` is *always* used when writing the options to disk. If you want to actually execute `config.cfg` from the console you can still do so by appending `pls` to the command:
![exec_pls](https://user-images.githubusercontent.com/5121829/151657329-9b0f21b4-d8a2-4498-82ba-f6981a092289.png)
