### ISSUE TITLE
Crash on load quicksave

### ISSUE THREAD

**Issue by 4LT** [andrei-drexler/ironwail#311]
Build: Latest, Master branch
OS: LInux

![image](https://github.com/andrei-drexler/ironwail/assets/3385021/15701caa-57a2-4eb9-b6bf-c4266472bcde)

Attempts to load quicksave on the map "Replicon" results in a crash with dialog box shown in the screenshot

[replicon_quicksave.zip](https://github.com/andrei-drexler/ironwail/files/14730097/replicon_quicksave.zip)

**Comment by alexey-lysiuk** [comment]
Add `-heapsize 1048576` to command line options. This increases heap size to 1 GB from default of 384 MB.
You can experiment with the value if you want. Probably, 512 MB (`-heapsize 524288`) will be enough for this map.

**Comment by 4LT** [comment]
I tried setting `-heapsize 1048576` but I still get the same behavior

**Comment by 4LT** [comment]
Ahh, no, I figured it out, I wasn't on the master branch after all, it was my own branch.

**Comment by 4LT** [comment]
Ack!  Re-compiled with the latest changes *I'm sure I'm on the master branch this time* and it's occurring again.  WTF is going on?  -heapsize still has no effect

gcc --version:
`gcc (GCC) 13.2.1 20230801`

In case this is a mis-compile

**Comment by Placo** [comment]
I've had the same issue in the map "Gibtropolis" recently. I loaded another save then and forgot about he issue.
Just now I have the same problem in ad_tears with an autosave. I have tried to increase heapsize but I get the crash "Z_Realloc: failed on allocation of 243712 bytes" consistently while trying to load that autosave. 
I was using the windows x64 ironwail.exe compiled by me in VS2022 with the latest source.
I have tried using the exe in the artifacts of the latest CI here but I have the exact same error trying to load that save.

Here is that save in a zip file:
[ad_tears.zip](https://github.com/andrei-drexler/ironwail/files/14780057/ad_tears.zip)

**Comment by Placo** [comment]
I have narrowed it down to commit 64c819f
Versions before that commit load my save file, but versions after crash...

**Comment by 4LT** [comment]
apparently it depends on my working directory whether or not the crash occurs;

If my CWD is my ironwail directory (~/.ironwail), loading the save will cause a crash.

If my CWD is something else, loading the save does not cause a crash.

**Comment by andrei-drexler** [comment]
Thanks for looking into this, folks, I'll try to repro this again with the new info.

**Comment by andrei-drexler** [comment]
@Placo You mentioned you were running the Win64 version - could you share how your Quake dir is set up, where the executable is relative to that, and how you're launching it? I'm hoping to repro this on Windows, so I can use the VS debugger.

**Comment by Placo** [comment]
Hello @andrei-drexler , sorry for the late answer I was off the internet for a few days.
I am using a "legacy" dir set up, that's more or less the same folder I've been hauling from HDD to HDD since the late 90s (with a few cleanups ofc)
ie:

- Quake
  - ID1
  - (a whole lot of mod folders, I suspect they might be the trigger for the bug, ie;)
  - AD180
  - Alkaline
  - Copper
  - Dwell
  - [...] (as in a total of 128 mod folders worth a whopping 45Gb)
  - Ironwail .exe, .pak and binaries directly here (in Quake/ )
  - SQLLauncher2.exe (Simple Quake Launcher, https://github.com/m-x-d/Simple-Quake-Launcher-2/releases/tag/2.7)

The autosave I linked earlier still crashes with that big folder (having restarted Windows multiple times since).
I have the crash launching Ironwail with only basic command line params ("ironwail.exe  -width 2560 -height 1440  -game ad180  +skill 2  +map start").

I have tried to make a minimal repro Quake folder by just copying the ID1, AD180 folders, the latest Ironwail binaries and Simple Quake Launcher in a new folder, but I don't get the crash there.
I am beginning to think in my case the whole mass of mod folders is what is causing latest Ironwail to break a sweat.

**Comment by andrei-drexler** [comment]
Thanks for the details, @Placo. I was finally able to repro this be creating a few copies of my ad directory, and then abusing the -basedir argument to use the same working directory multiple times. The issue should be fixed in b44479827dcdd6493de902efbca12110f7840316.
