### ISSUE TITLE
[Bug] Particle trail density on projectiles tied to framerate

### ISSUE THREAD

**Issue by h4724** [andrei-drexler/ironwail#33]
The particles emitted by projectiles that leave trails (grenades, rockets, gibs etc) are created at a higher frequency when playing at higher framerates. This can lead to the particle limit being hit very easily - if you don't mess with heapsise - so no more particles are generated, not to mention it looks ugly to see a solid line of particles.

As far as I can tell this bug exists in every engine, but it's only a problem when playing at high FPS, which is particularly apparent in this one. It would be nice to finally see a fix for it.

![FPS uncapped](https://user-images.githubusercontent.com/93443653/151686786-2f90caa2-0c94-47da-9bcd-7e7005d397c2.png)
![FPS capped at 72](https://user-images.githubusercontent.com/93443653/151686788-e8b5f5d3-d9a9-47d6-9c6e-218da212348e.png)

**Comment by andrei-drexler** [comment]
Fixed in https://github.com/andrei-drexler/ironwail/commit/cefe958ec4ab2fcedc45f3a471a35ba9857b752b

**Comment by andrei-drexler** [comment]
You're right, and I am aware of this clumping effect, it's just at at this point people have been playing Quake at 60+ fps for a really long time, so they're used to seeing continuous trails. If I were to make this change I'd expect to get bug reports that the trails look weird. I guess a lower rate for r_softemu 3 could make sense, though.

PS my initial implementation actually had a cvar controlling this, but I removed it at the last minute since I want to keep the code as simple as possible, and 72 fps is consistent with what QS looks like by default.

**Comment by h4724** [comment]
I'd prefer at least separate cvars, even if you roll them into one menu option. I'd prefer that approach in general actually, as opposed to all of the disparate elements that you're putting under r_softemu (palletised lighting, screen space dithering, texture space dithering, UV distortion etc)

**Comment by mhQuake** [comment]
I'd love to find it as well, because I remember it so distinctly. It might be in Masters of Doom (must get an electronic copy) or some contemporary interview. It's not in The Egos At Id: I just checked.

In it he describes shooting a grenade or a rocket, how the particle trail forms behind it, and how each clump is intended to give the illusion of a smoke puff.

On reflection it is correct to observe that the continuous trail at 72fps is what people are used to, and running it slower would only cause bugs to be raised. Even if Carmack himself stood up tomorrow and said continuous was wrong, people would probably still complain.

If it were to be cvar-ized at all, I think only 2 settings would make sense: 36 or 72. And now I just know there's someone who'd prefer the old high FPS behaviour.
