### ISSUE TITLE
Does ironwail include the improvements from quakespasm SPIKED?

### ISSUE THREAD

**Issue by NastyFlytrap** [andrei-drexler/ironwail#331]
Mainly asking about the physics being uncoupled from the framerate thing, but the other neat features of spiked would be cool too!

**Comment by h4724** [comment]
Yes, the physics and framerate are separate in IW. I don't know all of the features of QSS but almost all of them should be here. The only notable absence that I'm aware of is that the client-side QuakeC support is limited to the HUD - so Arcane Dimensions' fancy particle effects are unsupported, for instance.

**Comment by NastyFlytrap** [comment]
> Yes, the physics and framerate are separate in IW. I don't know all of the features of QSS but almost all of them should be here. The only notable absence that I'm aware of is that the client-side QuakeC support is limited to the HUD - so Arcane Dimensions' fancy particle effects are unsupported, for instance.

Ah. Thats a real shame because i was going to *eventually* create a duplicate version of the game's code, where i mod the original nightmare difficulty properties into the new expansion, because i really want to play that, but i dont want to play with the new difficulty they retconned into the game, and as far as i know, reversing that is only possible by editing the original source code of Quake, hacking that into the expansion's data file, and running that

**Comment by h4724** [comment]
I don't see the connection between your reply and my comment? Modding the nightmare mode of Dimension of the Machine to match the original game has nothing to do with network/renderer isolation _or_ CSQC support. Since you asked, those nightmare changes are in the QuakeC, not the engine code. [You can find it on id Software's github](https://github.com/id-Software/quake-rerelease-qc/tree/main/quakec_mg1).

**Comment by NastyFlytrap** [comment]
> I don't see the connection between your reply and my comment? Modding the nightmare mode of Dimension of the Machine to match the original game has nothing to do with network/renderer isolation _or_ CSQC support. Since you asked, those nightmare changes are in the QuakeC, not the engine code. [You can find it on id Software's github](https://github.com/id-Software/quake-rerelease-qc/tree/main/quakec_mg1).
I guess thats just because i dont know what im doing or how to do what i want to do, so i cant explain it properly to someone who knows what they are doing. But yea, i just want to play the new expansion with the old nightmare settings, and i dont know how to do that.

**Comment by NightFright2k19** [comment]
FTE extensions are apparently not supported. I recently tried to code a progs.dat mod with footsteps changing based on the surface you walk across. This is currently not possible with Ironwail.

**Comment by NastyFlytrap** [comment]
> FTE extensions are apparently not supported. I recently tried to code a progs.dat mod with footsteps changing based on the surface you walk across. This is currently not possible with Ironwail.

Well thats a real bummer but im sure it'd be supported in the future anyway, and for the time being i could just use QSS to play it with that.

Im not sure how excessive it'd be. I know i looked at the code like two years ago and saw that the individual changes were scattered over a bunch of files instead of being in one difficulty file

**Comment by NightFright2k19** [comment]
Remaster with old Nightmare mode might be possible if there's a list somewhere which source files were changed (and ideally how). A new progs.dat could be compiled with the right code adjustments.

**Comment by NastyFlytrap** [comment]
> Remaster with old Nightmare mode might be possible if there's a list somewhere which source files were changed (and ideally how). A new progs.dat could be compiled with the right code adjustments.

Yea, in theory its possible but, im no a developer. I worked out how to compile quakeC and look at the original source code, and thats pretty much as far as i got.

Maybe extract the progs.dat from the remaster, extract it from the original files too, and compare the two?

**Comment by NightFright2k19** [comment]
The Nightmare changes are mostly based on those made by Copper. Maybe Lunaran could help identify the code lines which have been adjusted. Once you know that, it's relatively easy to edit the affected lines and recompile the Remaster source (which is gratefully available since a while).

**Comment by NastyFlytrap** [comment]
> The Nightmare changes are mostly based on those made by Copper. Maybe Lunaran could help identify the code lines which have been adjusted. Once you know that, it's relatively easy to edit the affected lines and recompile the Remaster source (which is gratefully available since a while).

Alright, well, i suppose i'll just have to ask them then

**Comment by NightFright2k19** [comment]
@NastyFlytrap 
I had some spare time and did it by myself. Went through the source files and identified the spots where Nightdive applied changes and reversed them.

How to make it work:
1) [Downlad this (600 KB)](https://mega.nz/file/ZNIG1SrB#K7HWlgpAeG8_e16YOYtz3g7kFR4KEB7Ty63L7BhRqo8) and unzip it into your Quake installation dir. (Make sure you don't have any "pak1.pak" files there already which might get overwritten .)(shouldn't be the case unless you've already installed modifications)
2) When ingame, type this into the console: **oldnmare 1** 
3) Start the game with Nightmare mode.

Notes:
1) The included progs.dat files are based on latest QuakeEX release. Supported are: Quake, SoA, DoE, DOPA, MG1.
2) The CVAR isn't saved to config and defaults to 0, so if you want to play vanilla Nightmare, you have to set oldnmare to 1 for every game session. I believe it's a fair compromise.
3) I have removed the Achievement system completely since it is useless in custom ports, for which this is intended. If you want to use this with QuakeEX and you need the Achievements back badly, I can recompile a version which brings them back.
4) I've also included an adjusted version of "Beyond Belief" since it almost uses the same code as ID1. If you don't need it, delete the "bbelief" folder again.

**Comment by NastyFlytrap** [comment]
> @NastyFlytrap I had some spare time and did it by myself. Went through the source files and identified the spots where Nightdive applied changes and reversed them. I have created a solution which allows you to actually choose which Nightmare mode you want to use.
> 
> How to make it work:
> 
>     1. [Download this (600 KB)](https://mega.nz/file/gE4jFZTT#0tYTOcVtZfl3PCEEFfwETOvjS2SJV6QgVaOaCiVnIHM) and unzip it into your Quake installation dir. (Make sure you don't have any "pak1.pak" files there already which might get overwritten. Shouldn't be the case unless you've already installed modifications.)
> 
>     2. When ingame, open the console (^) and type this (confirm with "Enter"): **oldnmare 1**
> 
>     3. Start the game in Nightmare mode.
> 
> 
> Notes:
> 
>     1. The included progs.dat files are based on latest QuakeEX release. Supported are: Quake, SoA, DoE, DOPA, MG1.
> 
>     2. The CVAR isn't saved to config and defaults to 0, so if you want to play vanilla Nightmare, you have to set oldnmare to 1 for every game session. (It may be carried over across savegames, haven't tested that.) I believe it's a fair compromise.
> 
>     3. I have removed the achievement system completely since it is useless in non-Kex ports, for which this is intended. If you want to use this with QuakeEX and you need achievements badly, I can recompile a version which brings them back.
> 
>     4. I've also included an adjusted version of "Beyond Belief" since it uses almost the same code as ID1. If you don't need it, delete the "bbelief" folder again. It includes an important sound-related fix which resolves crashes in custom ports after defeating Chthon in the last level, though, so it's not so irrelevant.

This is so nice of you to do, but i have a few questions:
1: If i have a save i saved with old nightmare on, and then i relaunch the game, do i type it in, on the main menu screen and then load the save, or how does that work exactly when im not starting a new playthrough, and going through the difficulty selection map?
2: I do have a pak1 file in id1, for some reason, but i dont remember what it does, so that kinda sucks. I need to figure out how to open it and see whats in there. Its like 33mb's but i know i never installed any mods beyond level packs
3: Is it possible for this to support Epochs of enmity and Abyss of pandemonium too? You know, the now unofficial 7th episode, which was intended to be the 5th and then machine games did their thing, and the unofficial third mission pack
4: I see you support beyond belief in the zip but you didnt mention that near the included progs.dat files. Was this a late addition to the download, after you wrote this?
5:How did you figure out which lines nightdive changed?

**Comment by NightFright2k19** [comment]
1) You can enter the command at any time, but it's possible the effects won't take effect before the next map is loaded. The health cap should be gone right away, at least.

2) You can name my patches differently, e.g. pak2.pak. Use SLADE3 to open pak files, it's a great tool which works with far more than just Doom.

3) I dunno if EoE and AoP got special QuakeEX re-releases. If they did, adjustments can only be made if the source is also included (which was the case for Bbelief). The original releases shouldn't require modding since they are based on vanilla QC.

4) I mentioned BBelief is included in my previous post. Mind that I reuploaded everything a few hours ago since I had made a major mistake in subs.qc which screwed up the monster refiring process.

5) I basically checked for "skill" in the source files and compared the QuakeEX versions with vanilla. Gratefully Nightdive also commented some sections they changed, which made it easier. Not many files are affected. Basically client.qc, subs.qc and two monsters (shambler.qc, vore.qc). Combat.qc contains code as well, but it remained unaltered.

6) If you mean the localized texts for intermissions etc: Those could be changed in the source, but it wouldn't fix everything. Many loca keys are inside of the maps themselves, which makes things complicated. One would have to extract .ent files from all maps and replace all the placeholders with English text. It's far easier to simply take QuakeEX.kpf from the Remaster and place it in your Quake dir. Ironwail will recognize it. Technically you just need the "localization" folder (it's a renamed zipfile), but repacking it is probably needless for the average user.

**Comment by NastyFlytrap** [comment]
> 1. You can enter the command at any time, but it's possible the effects won't take effect before the next map is loaded. The health cap should be gone right away, at least. However, saves that were made with a different progs.dat can cause issues. I've made bad experiences with it and can only recommend to use this when starting over.
> 
>     2. You can name my patches differently, e.g. pak2.pak. Use [SLADE3](https://slade.mancubus.net/index.php?page=downloads) to open pak files, it's a great tool which works with far more than just Doom.
> 
>     3. I dunno if EoE and AoP got special QuakeEX re-releases. If they did, adjustments can only be made if the source is also included (which was the case for BBelief). The original releases which you can download on Quaddicted or Slipseer (among others) shouldn't require modding since they are based on vanilla QC.
> 
>     4. I mentioned BBelief is included in my previous post. Mind that I reuploaded everything a few hours ago since I had made a major mistake in subs.qc which screwed up the monster refiring process.
> 
>     5. I basically checked for "skill" in the source files and compared the QuakeEX versions with vanilla. Gratefully Nightdive also commented some sections they changed, which made it easier. Not many files are affected. Client.qc, subs.qc and two monsters (shambler.qc, vore.qc). Combat.qc contains code as well, but it remained unaltered.
> 
>     6. If you mean the localized texts for intermissions etc: Those could be changed in the source, but it wouldn't fix everything. Many loca keys are inside of the maps themselves, which makes things complicated. One would have to extract .ent files from all maps and replace all the placeholders with English text. It's far easier to simply take QuakeEX.kpf from the Remaster and place it in your Quake dir. Ironwail will recognize it. Technically you just need the "localization" folder inside the kpf (it's a renamed zipfile), but repacking it is probably needless for the average user.
> 
> 
> Note: QuakeEX doesn't require a pak1.pak in the id1 folder. Everything is inside pak0.pak. If your version requires pak1.pak, you are running vanilla and this whole mod is useless. You shouldn't mix vanilla and Remaster stuff, either. Use only QuakeEX paks or only vanilla assets.

1: Alright, makes sense, noted. Thanks
2:Ah, i see. I didnt know SLADE supported Quake, good to know!
3: Nope, they did not.
4: Alright, sorry, it just wasnt among the list of things the progs.dat was based on
5: I remember looking at those, but they were long files and i didnt have an easy comparison tool to see which lines changed so i got filtered quick...
6: I could have sworn i moved some other files from the remaster to the ironwail/QSS folder not just the pak files, but i guess it must have been something else

What do you mean by vanilla exactly?

**Comment by NightFright2k19** [comment]
Any mods released separately, i.e. outside of the Nightdive port, available from websites, are guaranteed to be based on old code, i.e. old Nightmare mode. This definitely applies for EoE and AoP. The latter received some fan patch a few years ago, btw.

With "vanilla" I'm basically referring to the original release of the game, before the Remaster. It came with two pak files in the id1 folder, maps didn't have fog, colored lights, transparent water or external localization. If you're using that, you automatically have the old Nightmare mode, ofc. You could also run DOPA or MG1 with it, but they would require QuakeEX.kpf (DOPA was also available as a standalone release, but it's missing some features compared to the version that came with the Remaster).

**Comment by NastyFlytrap** [comment]
> Any mods released separately, i.e. outside of the Nightdive port, available from websites, are guaranteed to be based on old code, i.e. old Nightmare mode. This definitely applies for EoE and AoP. The latter received some fan patch a few years ago, btw.
> 
> With "vanilla" I'm basically referring to the original release of the game, before the Remaster. It came with two pak files in the id1 folder, maps didn't have fog, colored lights, transparent water or external localization. If you're using that, you automatically have the old Nightmare mode, ofc. You could also run DOPA or MG1 with it, but they would require QuakeEX.kpf (DOPA was also available as a standalone release, but it's missing some features compared to the version that came with the Remaster).

Ah, yea. I thankfully already found the 2.0 patch for AOP

Alright, thanks for the explanation, and the mod, i've been wanting this for like three years and never got around to making it myself because learning coding and QuakeC specifically for this was just too hard to convince myself to do

**Comment by NightFright2k19** [comment]
I had already done a patch for Shrak, which included decompiling the source and reconstruct large parts of missing code. Eventually you learn something. XD

**Comment by NastyFlytrap** [comment]
> I had already done a patch for Shrak, which included decompiling its progs.dat and reconstructing large parts of missing code. Eventually you learn something. XD

Whats the story behind that? Why was it missing code? What was the patch about?

**Comment by NightFright2k19** [comment]
The patch basically tackles everything that was still annoying about the game.

[This thread in the QuakeOne forums](https://quakeone.com/forum/quake-mod-releases/finished-works/281923-inofficial-shrak-v2-1-patch) probably covers it all, enjoy reading.

**Comment by NastyFlytrap** [comment]
> The patch basically tackles everything that was still annoying about the game.
> 
> [This thread in the QuakeOne forums](https://quakeone.com/forum/quake-mod-releases/finished-works/281923-inofficial-shrak-v2-1-patch) probably covers it all, enjoy reading.

Alright, thanks for the mod and the story!
