### ISSUE TITLE
Names in mod menu not respecting "dir"

### ISSUE THREAD

**Issue by h4724** [andrei-drexler/ironwail#334]
As far as I can tell, the "proper" name for each mod in the mods menu is taken from the "name" line in mapdb.json in the mod's folder, if there is one. Unfortunately, this means that if that file is packaged as part of a mod, and the mod is then packaged with another map pack, they will show as having the same name in the IW mods menu. For instance, I have lots showing up as "Underdark Overbright" when that should only be copper. If this isn't the cause, I don't know what else it could be.

I can't think of a reason why they should package the mapdb.json really, but this could still be avoided if Ironwail read the "dir" line in the same file and ignored the file if it didn't match the mod directory that it was in.

**Comment by andrei-drexler** [comment]
IW does read the "dir" field, but in order to allow people to rename their mods without losing their descriptions it only requires dir matches in some cases. One of those cases is exactly this - Copper's mapdb.json being included in other mods: https://github.com/andrei-drexler/ironwail/blob/38667985b0e63dde5f8752477fdd4fa3865ddd5d/Quake/host_cmd.c#L1151-L1159
Unfortunately, there was also a bug in that code, should be fixed in https://github.com/andrei-drexler/ironwail/commit/0c50bc0f9acf2ccf08b10ecdd98990025e610e3b.
