### ISSUE TITLE
Implement a versioning system that takes into account commit hashes

### ISSUE THREAD

**Issue by garoto** [andrei-drexler/ironwail#42]
Perhaps this should belong to sezeros quakespasm tree, but in any case, can we have a versioning system sitting outside "version.h" hardcoded strings? Something that'd update "IRONWAIL_VER_SUFFIX" during compiling time with the result of a `git describe --always` output?

n.b.: I'm not a computer programmer in any way, but its tiresome to build different quakespasm versions and being unable to tell witch git ccommit I'm testing....

**Comment by garoto** [comment]
I imagine the whole versioning sytem would have to be redone from scratch?

**Comment by garoto** [comment]
Figured I can achieve this myself with a `sed` expression and then just resetting the branch afterwards.

**Comment by andrei-drexler** [comment]
A simple solution would be to add
```makefile
CFLAGS += -DIRONWAIL_VER_SUFFIX=\"-$(shell git describe --always)\"
```
somewhere in the makefile, maybe [here](https://github.com/andrei-drexler/ironwail/blob/31f10f656218a84957e0c8c951ea71e214ba7aa9/Quake/Makefile#L70). The tricky part is avoiding stale data in partial builds, but since full rebuilds are actually pretty fast (with -j), you could just run a `make clean` before compilation.

I intend to make a shell script that will handle this (and then setup github actions), but I started with the windows build first, since that's the more popular option. I actually have a WIP bat script + custom props for MSVC, but they're not quite ready yet.

PS Sorry for taking so long to reply, I'm running kind of low on energy lately, so I've been mostly dealing with the easier issues that I can handle right away.

**Comment by garoto** [comment]
`CFLAGS += -DIRONWAIL_VER_SUFFIX=\"-$(shell git describe --always)\"`

Sweet, this worked great haha, thanks a bunch! btw, I'm on Windows as well, but cross-compile using Makefile.w64.

> PS Sorry for taking so long to reply

Hey, no worries my dude. I figured it is a pretty niche and low priority feature to be worked on.
