### ISSUE TITLE
Display monster counts > 3 digits in intermission

### ISSUE THREAD

**Issue by h4724** [andrei-drexler/ironwail#68]
Since it's getting more common for maps to have over 1000 enemies, it'd be nice to have the score screen properly display these numbers. Currently it only displays the last 3 digits, so if you had 1234 enemies it would display the total as 234.

**Comment by Lain-tf** [comment]
This would be a great feature. Especially for large-scale projects like Dwell, SMEJ and Ter Shib.

**Comment by mhQuake** [comment]
This needs to be in the status bar as well. 

I'd add to this: don't show total monsters if it's 0, and likewise with secrets. This came up during RMQ development when the creators were using QC tricks to hide the total counts, but it also looks neater for maps like start.bsp where they can just show "0" instead of "0/0".

**Comment by h4724** [comment]
> This needs to be in the status bar as well.

Status bar already works fine with high monster counts?

**Comment by Lain-tf** [comment]
> Reminds me: also need to check if savegame comments need support for counts over 999.
Yup, works perfectly.
![image](https://user-images.githubusercontent.com/19338861/162121130-bc4893d9-f9a8-4e08-bb8d-7d9e8920f556.png)

**Comment by andrei-drexler** [comment]
Fixed in 85d042a2ccca4277d190cfa19c9a0699f8ecae0c, and while at it I've also tweaked the alignment:

<table>
<thead><tr><th>Before</th><th colspan=3>After</th></tr></thead>
<tbody><tr>
<td><img src="https://user-images.githubusercontent.com/5121829/162627184-7d2a1195-1618-4c7e-97fd-a7d04d30a440.jpg"/></td>
<td><img src="https://user-images.githubusercontent.com/5121829/162625889-b80523f9-a747-4c2d-863d-6cb430e94df7.jpg"/></td>
<td><img src="https://user-images.githubusercontent.com/5121829/162625908-91753c2a-0bc2-422b-96fe-0d74a33bb723.jpg"/></td>
<td><img src="https://user-images.githubusercontent.com/5121829/162625923-3f9485a7-cf42-4af1-9ffb-76c65a6974b6.jpg"/></td>
</tr></tbody>
</table>

<hr/>

> This needs to be in the status bar as well.

> Status bar already works fine with high monster counts?

Status bar did indeed support high counts, but there was some overlap with the skill text at 4 digits (fixed in c143922513910e46cd4a14e08c6ee5e7753ef0b6 - now the skill info is centered in-between the monster/secret counts):
![sb_overlap](https://user-images.githubusercontent.com/5121829/162627472-746d6b9b-ccd3-479b-8ff4-8bf7c84eea18.jpg)
![sb_no_overlap](https://user-images.githubusercontent.com/5121829/162627476-16a72275-a25b-4677-8bc4-8ab930236219.jpg)

<hr/>

> I'd add to this: don't show total monsters if it's 0, and likewise with secrets. This came up during RMQ development when the creators were using QC tricks to hide the total counts (I don't necessarily agree with doing that because I think the sense of progression is an important part of the game), but it also looks neater for maps like start.bsp where they can just show "0" instead of "0/0".

This would probably look cleaner, but I think it could also confuse some players ("0 out of what? Why am I not seeing the totals?"), so I'd rather avoid the inconsistency.
